[tools]
age = "latest"
ant = "latest"
bun = "latest"
claude-code = "latest"
deno = "latest"
gh = "latest"
go = "latest"
gopass = "latest"
java = "latest"
openbao = "latest"
opencode = "latest"
opentofu = "latest"
pnpm = "latest"
prek = "latest"
python = "latest"
ruff = "latest"
rust = "latest"
sops = "latest"
terraform-ls = "latest"
usage = "latest"

[settings]

[settings.npm]
bun = true
