[tools]
age = "latest"
ant = "latest"
bun = "latest"
claude-code = "latest"
deno = "2.2.1"
go = "latest"
gopass = "latest"
java = "25"
openbao = "latest"
opencode = "latest"
opentofu = "1.9.0"
pnpm = "latest"
rust = "latest"
sops = "latest"
terraform-ls = "0.36.4"
usage = "2.0.5"

[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.npm]
bun = true

[env]
